### ISSUE TITLE
Regression: crash when importing `@threlte/theatre` + broken demo due to import changes in PR #1648

### ISSUE THREAD

**Issue by danielegarciav** [threlte/threlte#1659]
As of `@threlte/theatre` 3.1.0, importing `@threlte/theatre` crashes the app. The [demo for `<SoftShadows>`](https://threlte.xyz/docs/reference/extras/soft-shadows) is broken [(link to StackBlitz project)](https://stackblitz.com/edit/gn2xz5ew?file=src%2Fexample%2FApp.svelte).

In the demo project, the following error is printed to the console:
```
InnerStudio-R666PK4S.js?v=dc8aa5e3:41 Uncaught (in promise) TypeError: Studio.initialize is not a function
```

Digging into this error, I can see that in `@threlte/theatre`, `InnerStudio.svelte` dynamically imports `@theatre/studio`, and then assumes the result of the dynamic import is the default export itself, but this assumption does not hold in either the demo project nor a freshly created Svelte project using `npx sv create` (version 0.10.4).

Making this local patch in `node_modules/@threlte/theatre/dist/studio/InnerStudio.svelte` (using eg `bun patch`) fixes the problem for me:

```diff
   const studioModule = await import('@theatre/studio')
-  const Studio = studioModule as unknown as typeof import('@theatre/studio').default
+  const Studio = studioModule.default
   import { studio } from '../consts.js'
 
   Studio.initialize()
```

It seems this regression was caused by https://github.com/threlte/threlte/pull/1648, in particular this commit https://github.com/threlte/threlte/pull/1648/commits/4856710019119c704a23227db3c6313be44ba5af.

Perhaps @helgee could confirm whether the assumption _should_ hold (and we're looking at possibly tsconfig/bundler misconfiguration), or if the assumption should not hold, and the patch above points towards the ideal fix.

**Comment by michealparks** [comment]
This fix makes sense, making a release right now, thank you so much for reporting!

**Comment by danielegarciav** [comment]
@michealparks the issue is somehow still ongoing, and somehow it got more bizarre:

<img width="433" height="149" alt="Image" src="https://github.com/user-attachments/assets/f15dbc28-d25c-41ed-89a6-74b2bda8048f" />

Somehow the result of the dynamic import is an object that looks like `{ default: { default: { ... } }`... and the code in `InnerStudio.svelte` somehow expects to receive what is now `studioModule.default.default`. Something weird is going on.

The demo for `<SoftShadows>` at https://threlte.xyz/docs/reference/extras/soft-shadows is still broken, the screenshot above comes from the debugger on that project. StackBlitz link: https://stackblitz.com/edit/xut4vefx-ur1hdcda?file=package.json

**Comment by helgee** [comment]
Hi, sorry for the breakage. I have opened a new PR which patches `@theatre/studio` and removes my brittle workaround.

**Comment by DefinitelyMaybe** [comment]
@danielegarciav hopefully all sorted with the newest patch 3.1.2, let us know how it goes.

**Comment by danielegarciav** [comment]
@DefinitelyMaybe @helgee the PR fixes this issue! Specifically, downloading the StackBlitz project, fixing asset references and explicitly using @threlte/theatre 3.1.2 works perfectly, out of the box with no need to patch any dependencies on my part.

<img width="1686" height="1059" alt="Image" src="https://github.com/user-attachments/assets/415c940b-a145-4c2c-a321-2911b73a8705" />

The `<SoftShadows>` demo page is still broken at https://threlte.xyz/docs/reference/extras/soft-shadows but I imagine that's a matter of redeploying with this update.

**Comment by michealparks** [comment]
Thanks for the fix @helgee!
